/**
 * Base Template Module
 * 
 * Provides base HTML document templates and common structures
 * used across different print document types.
 */

import { format } from 'date-fns';

import { escapeHtml } from '../../sanitization';
import type { DocumentMetadata } from '../types';
import { TemplateType } from '../types';

/**
 * Creates a complete HTML document with proper structure
 * 
 * @param title - Document title (appears in browser tab and print header)
 * @param styles - CSS styles to include in the document head
 * @param body - HTML content for the document body
 * @param metadata - Optional document metadata
 * @returns Complete HTML document string
 */
export function createBaseHTMLDocument(
  title: string, 
  styles: string, 
  body: string,
  metadata?: DocumentMetadata
): string {
  const metaTags = metadata ? createMetaTags(metadata) : '';
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  ${metaTags}
  <style>
    ${styles}
  </style>
</head>
<body>
  ${body}
</body>
</html>`;
}

/**
 * Creates meta tags for document metadata
 * 
 * @param metadata - Document metadata
 * @returns HTML meta tags string
 */
function createMetaTags(metadata: DocumentMetadata): string {
  const tags: string[] = [
    `<meta name="description" content="Generated ${metadata.type.replace('_', ' ')} document">`,
    `<meta name="generator" content="Teaching Engine 2.0">`,
    `<meta name="created" content="${metadata.generatedDate.toISOString()}">`
  ];
  
  if (metadata.author) {
    tags.push(`<meta name="author" content="${escapeHtml(metadata.author)}">`);
  }
  
  if (metadata.version) {
    tags.push(`<meta name="version" content="${escapeHtml(metadata.version)}">`);
  }
  
  return tags.join('\n  ');
}

/**
 * Creates a standard document wrapper with header and footer
 * 
 * @param content - Main document content
 * @param headerContent - Optional header content
 * @param footerContent - Optional footer content
 * @returns Wrapped document body content
 */
export function createDocumentWrapper(
  content: string,
  headerContent?: string,
  footerContent?: string
): string {
  const header = headerContent ? `<header class="document-header">${headerContent}</header>` : '';
  const footer = footerContent ? `<footer class="document-footer">${footerContent}</footer>` : '';
  
  return `
    ${header}
    <main class="document-content">
      ${content}
    </main>
    ${footer}
  `;
}

/**
 * Creates a standard Teaching Engine footer
 * 
 * @param documentType - Type of document for specific messaging
 * @param additionalInfo - Optional additional information
 * @returns Footer HTML string
 */
export function createTeachingEngineFooter(
  documentType?: TemplateType,
  additionalInfo?: string
): string {
  const currentDate = format(new Date(), 'MMMM d, yyyy');
  const currentTime = format(new Date(), 'h:mm a');
  
  let typeSpecificText = '';
  switch (documentType) {
    case TemplateType.ETFO_DAYBOOK:
    case TemplateType.ETFO_LESSON_PLAN:
    case TemplateType.ETFO_UNIT_PLAN:
    case TemplateType.LONG_RANGE_PLAN:
      typeSpecificText = ' • ETFO Planning for Student Learning Framework';
      break;
    default:
      typeSpecificText = '';
  }
  
  const additionalText = additionalInfo ? ` • ${additionalInfo}` : '';
  
  return `
    <div class="generated-note">
      Generated by Teaching Engine 2.0 on ${currentDate} at ${currentTime}${typeSpecificText}${additionalText}
    </div>
  `;
}

/**
 * Creates a print-optimized page structure
 * 
 * @param content - Page content
 * @param options - Page options
 * @returns Page HTML with print optimization
 */
export function createPrintPage(
  content: string,
  options: {
    pageBreakBefore?: boolean;
    pageBreakAfter?: boolean;
    noBreak?: boolean;
    className?: string;
  } = {}
): string {
  const classes: string[] = [];
  
  if (options.pageBreakBefore) {
classes.push('page-break');
}
  if (options.noBreak) {
classes.push('no-break');
}
  if (options.className) {
classes.push(options.className);
}
  
  const classAttr = classes.length > 0 ? ` class="${classes.join(' ')}"` : '';
  const pageBreakAfter = options.pageBreakAfter ? '<div class="page-break"></div>' : '';
  
  return `
    <div${classAttr}>
      ${content}
    </div>
    ${pageBreakAfter}
  `;
}

/**
 * Creates a responsive grid layout for content sections
 * 
 * @param sections - Array of section content
 * @param columns - Number of columns (1-4)
 * @param gap - Gap between sections
 * @returns Grid layout HTML
 */
export function createGridLayout(
  sections: string[], 
  columns: 1 | 2 | 3 | 4 = 2,
  gap = '1rem'
): string {
  const gridClass = `grid-${columns}-column`;
  const style = `style="gap: ${gap};"`;
  
  return `
    <div class="${gridClass}" ${style}>
      ${sections.join('\n')}
    </div>
  `;
}

/**
 * Creates a flexible section container
 * 
 * @param title - Section title
 * @param content - Section content
 * @param options - Section options
 * @returns Section HTML
 */
export function createFlexibleSection(
  title: string,
  content: string,
  options: {
    titleLevel?: 1 | 2 | 3 | 4 | 5 | 6;
    className?: string;
    noBreak?: boolean;
    collapsible?: boolean;
  } = {}
): string {
  const titleLevel = options.titleLevel || 2;
  const classes: string[] = ['flexible-section'];
  
  if (options.className) {
classes.push(options.className);
}
  if (options.noBreak) {
classes.push('no-break');
}
  if (options.collapsible) {
classes.push('collapsible');
}
  
  const classAttr = ` class="${classes.join(' ')}"`;
  
  return `
    <section${classAttr}>
      <h${titleLevel} class="section-title">${escapeHtml(title)}</h${titleLevel}>
      <div class="section-content">
        ${content}
      </div>
    </section>
  `;
}

/**
 * Creates a standardized info card
 * 
 * @param items - Array of key-value pairs
 * @param columns - Number of columns for layout
 * @returns Info card HTML
 */
export function createInfoCard(
  items: { label: string; value: string; emphasis?: boolean }[],
  columns = 2
): string {
  const gridClass = columns === 1 ? 'info-single-column' : 
                   columns === 3 ? 'info-three-column' : 
                   columns === 4 ? 'info-four-column' : 'info-two-column';
  
  const itemsHtml = items.map(item => {
    const valueClass = item.emphasis ? 'info-value emphasized' : 'info-value';
    return `
      <div class="info-item">
        <span class="info-label">${escapeHtml(item.label)}</span>
        <span class="${valueClass}">${escapeHtml(item.value)}</span>
      </div>
    `;
  }).join('');
  
  return `
    <div class="info-card ${gridClass}">
      ${itemsHtml}
    </div>
  `;
}

/**
 * Template validation helper
 * 
 * @param requiredFields - Fields that must be present
 * @param data - Data object to validate
 * @returns Validation result
 */
export function validateTemplateData(
  requiredFields: string[],
  data: Record<string, unknown>
): { isValid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  requiredFields.forEach(field => {
    const value = data[field];
    if (value === undefined || value === null || (typeof value === 'string' && value.trim() === '')) {
      errors.push(`Required field '${field}' is missing or empty`);
    }
  });
  
  return {
    isValid: errors.length === 0,
    errors
  };
}