-- Fix all 8 Long Range Plans with proper pedagogical components
-- This script adds thematicOverview, assessmentStrategy, indigenousPerspectives, 
-- resourceLibrary, parentCommunication, and differentiationFramework to each plan

-- 1. FRANÇAIS LANGUE PREMIÈRE
UPDATE LongRangePlan SET 
  thematicOverview = 'French language development through rich thematic units: September - Ma rentrée (Back to School) with classroom routines and greetings; October - Les couleurs de l''automne (Fall Colors) with seasonal vocabulary; November - Ma famille et moi (My Family and Me) exploring relationships; December - Les fêtes et traditions (Holidays and Traditions) with cultural celebrations; January - L''hiver magique (Magical Winter) with weather and activities; February - Les amis et l''amitié (Friends and Friendship) focusing on social connections; March - Le printemps arrive (Spring Arrives) with growth and change; April - Les animaux de notre monde (Animals of Our World) with nature exploration; May - Ma communauté (My Community) with local connections; June - Nos souvenirs et notre avenir (Our Memories and Future) reflecting on learning.',
  
  assessmentStrategy = 'Comprehensive French language assessment through multiple modalities: ORAL COMMUNICATION - Daily circle conversations, weekly "Show and Tell" in French, monthly oral storytelling assessments using photo prompts, peer conversations recorded for progress monitoring; READING - Running records with French leveled readers, phonics assessments for letter-sound recognition, sight word evaluations using high-frequency French words, comprehension checks through picture matching and retelling; WRITING - Developmental writing portfolios showing progression from drawing to letters to words, weekly journal entries with teacher conferencing, monthly writing tasks connected to thematic units, assessment of letter formation and French spelling patterns; LISTENING - Response to French instructions and stories, comprehension activities with audio books, following multi-step directions in French; PORTFOLIO ASSESSMENT - Student self-reflection using visual scales, parent conference evidence collection, celebration of growth over perfection.',
  
  indigenousPerspectives = 'Authentic integration of Mi''kmaq perspectives throughout French learning: Mi''kmaq place names in Prince Edward Island pronounced and learned alongside French geographical terms; Traditional Mi''kmaq storytelling methods incorporated into French oral traditions, with Elders invited to share stories that connect to our French thematic units; Seasonal teachings aligned with Mi''kmaq understanding of natural cycles while building French vocabulary for weather, animals, and activities; Mi''kmaq family structures and community values explored when learning French family vocabulary, honoring diverse family configurations; Traditional Mi''kmaq games translated into French instruction, supporting physical activity and language learning; Land-based learning acknowledging Mi''kmaq stewardship while developing French nature vocabulary; Seven Sacred Teachings discussed in developmentally appropriate ways, connecting to character education in French; Collaboration with local Mi''kmaq communities for authentic cultural exchange and French language practice opportunities.',
  
  resourceLibrary = 'Rich collection of authentic French materials: LITERATURE - French-Canadian picture books featuring diverse characters and PEI settings, traditional French fairy tales adapted for Grade 1, Indigenous stories available in French translation, wordless picture books for oral language development, French poetry and nursery rhymes with audio support; DIGITAL RESOURCES - French educational apps for phonics and vocabulary, virtual reality experiences of French-speaking communities, French children''s songs and videos from Radio-Canada, online French games for independent practice; MANIPULATIVES - Magnetic French letters and sounds, French alphabet puzzles and cards, dramatic play props with French labels, French number and color games, sensory bins with French vocabulary cards; AUTHENTIC MATERIALS - French food packages for environmental print, French maps and travel brochures, French children''s magazines and newspapers, cultural artifacts from French-speaking communities; TEACHER RESOURCES - French pronunciation guides and audio files, assessment rubrics for French language development, professional development materials for French immersion pedagogy.',
  
  parentCommunication = 'Comprehensive family engagement supporting French learning at home: WEEKLY COMMUNICATION - "Français à la maison" newsletter sent home every Friday with this week''s French phrases, simple activities families can do together, recommended French resources for home use, and celebration of student French learning achievements; MONTHLY WORKSHOPS - Family French learning sessions where parents learn basic French phrases to support their children, hands-on activities parents can replicate at home, cultural education about French-Canadian and global Francophone communities; HOME-SCHOOL CONNECTION - French phrase cards sent home for family practice, suggestion lists for French cartoons and music families can enjoy together, guidance for supporting French reading at home without fluency pressure; CELEBRATION EVENTS - Monthly "Café français" where families visit for French songs and simple conversations, family invitations to French cultural events and performances, showcase opportunities for students to demonstrate French learning; MULTILINGUAL SUPPORT - Recognition and celebration of families'' home languages, resources translated into multiple languages when possible, encouragement of multilingual identity as a strength.',
  
  differentiationFramework = 'Responsive instruction meeting diverse French learning needs: FOR EMERGING FRENCH LEARNERS - Heavy use of visual supports, gestures, and environmental print; partner support with stronger French speakers; simplified vocabulary and shorter phrases; multisensory learning through movement, music, and art; frequent repetition and modeling; celebration of attempts over perfection. FOR ADVANCED FRENCH LEARNERS - Extension activities with complex French texts; leadership opportunities helping classmates; creative projects requiring higher-order thinking in French; connections to French literature and culture beyond grade level; independent reading with French chapter books; opportunities to teach French concepts to others. FOR STUDENTS WITH LEARNING DIFFERENCES - Assistive technology for French language access; alternative communication methods when needed; modified writing expectations with focus on meaning over mechanics; sensory supports for regulation during French instruction; individualized goals aligned with IEP requirements. FOR ENGLISH LANGUAGE LEARNERS - Explicit connection between home languages and French; visual vocabulary supports in multiple languages; recognition that multilingual learners have unique strengths; culturally responsive teaching acknowledging diverse backgrounds; family communication in preferred languages when possible.'

WHERE subject = 'Français langue première';

-- 2. MATHÉMATIQUES  
UPDATE LongRangePlan SET 
  thematicOverview = 'Mathematical thinking development through monthly thematic exploration: September - Collections de la classe (Classroom Collections) exploring sorting, counting, and early number concepts using classroom objects; October - Régularités d''automne (Fall Patterns) discovering patterns in nature, leaves, and seasonal changes while building number sequences; November - Nombres dans notre vie (Numbers in Our Life) investigating how we use numbers at home, school, and in our community; December - Formes et décorations (Shapes and Decorations) exploring 2D and 3D shapes through holiday decorations and winter geometry; January - Mesures et comparaisons (Measurement and Comparisons) using non-standard units to measure classroom objects and comparing lengths, weights; February - Problèmes et solutions (Problems and Solutions) developing problem-solving strategies through real-world mathematical challenges; March - Géométrie dans notre monde (Geometry in Our World) identifying shapes and spatial relationships in architecture and art; April - Données et graphiques (Data and Graphs) collecting, organizing, and representing information about weather, growth, and spring observations; May - Argent et achats (Money and Shopping) exploring Canadian coins and simple transactions; June - Révision mathématique (Mathematical Review) consolidating learning through games, investigations, and mathematical celebrations.',
  
  assessmentStrategy = 'Comprehensive mathematical understanding through diverse assessment: PROBLEM-SOLVING ASSESSMENTS - Weekly open-ended math problems with multiple solution paths, monthly mathematical investigations with student explanations, photographic documentation of student thinking using manipulatives, audio recordings of mathematical reasoning and vocabulary use; PORTFOLIO DEVELOPMENT - Mathematical journal entries showing progression of understanding, collection of problem-solving strategies used throughout the year, student self-assessments using visual rubrics and reflection prompts, growth documentation from concrete to abstract thinking; PERFORMANCE TASKS - Monthly hands-on mathematical challenges, collaborative group problem solving with peer assessment, real-world application projects connecting math to daily life, mathematical art projects demonstrating geometric understanding; OBSERVATIONAL ASSESSMENT - Daily anecdotal notes during math centers and guided practice, checklist assessments for specific skill development, documentation of mathematical discourse and vocabulary use, observation of transfer between mathematical concepts; DIAGNOSTIC AND FORMATIVE - Number sense screenings at beginning, middle, and end of year, regular quick check-ins for computational fluency, misconception identification and targeted support planning.',
  
  indigenousPerspectives = 'Respectful integration of Indigenous mathematical traditions: Traditional Mi''kmaq counting systems and number concepts shared alongside French numbers, with attention to cultural protocols and community guidance; Mi''kmaq seasonal calendar and natural patterns explored through mathematical observation and data collection; Traditional games involving mathematical thinking, such as bowl games and counting games, learned with cultural context and respect; Indigenous approaches to spatial reasoning and geometry through traditional art, beadwork patterns, and architectural designs; Mi''kmaq astronomical knowledge connecting to time, measurement, and cyclical thinking; Land-based mathematics learning from traditional ecological knowledge about animal populations, plant cycles, and resource management; Seven Sacred Teachings incorporated into character development during mathematical collaboration and problem-solving; Invitation of Indigenous Knowledge Keepers to share traditional mathematical thinking when culturally appropriate; Recognition of different cultural approaches to mathematical problem-solving and number sense; Connection to Mi''kmaq place names involving numbers, distances, and geographical mathematical concepts.',
  
  resourceLibrary = 'Diverse mathematical resources supporting hands-on learning: MANIPULATIVES - Base-ten blocks, counting bears in multiple colors, pattern blocks and geometric shapes, number lines and hundreds charts, measuring tools including non-standard units, fraction pieces and pizza wheels, coin sets and play money, dice, dominoes, and number cards; GAMES AND PUZZLES - Mathematical board games supporting number sense, card games for computational practice, logic puzzles appropriate for Grade 1, technology-based math games and apps, outdoor math equipment for active learning; LITERATURE - Mathematical picture books in French and English, counting books with diverse characters and settings, shape and pattern books with engaging stories, problem-solving books encouraging mathematical thinking; TECHNOLOGY - Interactive whiteboards with mathematical software, tablets with math apps for independent practice, calculators for exploration and verification, digital timers and measuring tools; ASSESSMENT TOOLS - Observation forms for mathematical discourse, rubrics for problem-solving assessment, portfolio organization systems, student self-assessment visual tools; TEACHER RESOURCES - Professional development materials for mathematical pedagogy, cultural competency resources for inclusive teaching, assessment guides for developmental mathematics.',
  
  parentCommunication = 'Family engagement supporting mathematical learning: HOME-SCHOOL MATH CONNECTION - Weekly math activities families can do together using household items, monthly newsletters explaining mathematical concepts being learned and how to support at home, suggestions for mathematical conversations during daily routines like cooking and shopping, celebration of mathematical thinking over correct answers; FAMILY MATH EVENTS - Monthly family math nights with hands-on activities and games, workshops showing parents how children learn math today vs. traditional methods, cultural celebration events incorporating mathematical thinking from diverse traditions; COMMUNICATION STRATEGIES - Regular updates about mathematical milestones and growth areas, conference discussions focusing on mathematical thinking development, resource sharing for families wanting to support math learning, multilingual support when needed for mathematical communication; REAL-WORLD CONNECTIONS - Suggestions for finding math in everyday family activities, encouragement of mathematical questions and wondering, support for families in building positive mathematical identities; HOME LEARNING SUPPORT - Simple mathematical activities requiring no special materials, guidance for families with math anxiety or negative past experiences, celebration of family mathematical knowledge and problem-solving strategies.',
  
  differentiationFramework = 'Responsive mathematical instruction for diverse learners: FOR STUDENTS NEEDING ADDITIONAL SUPPORT - Extended time with concrete manipulatives before moving to abstract concepts; visual supports and graphic organizers for problem-solving; simplified mathematical language with key vocabulary emphasis; frequent opportunities for repetition and practice; peer buddy system for mathematical collaboration; celebration of mathematical thinking and effort over speed or accuracy. FOR MATHEMATICALLY ADVANCED STUDENTS - Open-ended problems with multiple solution paths; opportunities to explain mathematical thinking to peers; extension activities involving higher-order mathematical concepts; connections to real-world mathematical applications; independent mathematical investigations; leadership roles in mathematical discussions and problem-solving. FOR ENGLISH LANGUAGE LEARNERS - Mathematical instruction leveraging universal mathematical concepts; visual and hands-on approaches reducing language barriers; peer translation support when appropriate; celebration of home mathematical knowledge and problem-solving traditions; multilingual mathematical vocabulary development. FOR STUDENTS WITH LEARNING DIFFERENCES - Assistive technology for mathematical access; alternative assessment methods showing mathematical understanding; modified mathematical expectations aligned with individual learning goals; sensory supports during mathematical instruction; multi-modal mathematical instruction addressing different learning styles.'

WHERE subject = 'Mathématiques';

-- 3. SCIENCES DE LA NATURE
UPDATE LongRangePlan SET 
  thematicOverview = 'Seasonal inquiry-based exploration of natural world: September - Découverte de notre cour d''école (Discovering Our Schoolyard) through nature walks, observation journals, and collection of natural specimens; October - Changements d''automne (Fall Changes) investigating leaf transformations, animal preparations for winter, and seasonal weather patterns; November - Caractéristiques des êtres vivants (Characteristics of Living Things) exploring what makes something alive through plant and animal observations; December - Adaptation en hiver (Winter Adaptations) studying how plants and animals survive cold weather; January - Sources d''énergie autour de nous (Energy Sources Around Us) discovering how we use energy for heat, light, and movement; February - Cycle de l''eau en hiver (Winter Water Cycle) observing ice, snow, and water transformations; March - Signes du printemps (Signs of Spring) documenting emerging plants, returning animals, and changing daylight; April - Jardinage et croissance (Gardening and Growth) planting seeds and observing life cycles; May - Écosystème de notre communauté (Our Community Ecosystem) exploring local habitats and animal homes; June - Bilan scientifique (Scientific Summary) reflecting on seasonal observations and planning summer investigations.',
  
  assessmentStrategy = 'Inquiry-based assessment celebrating scientific thinking: SCIENCE JOURNALS - Daily nature observations with drawings and beginning scientific vocabulary, weekly wonder questions and predictions, monthly reflection on learning and discoveries, documentation of seasonal changes and patterns; HANDS-ON INVESTIGATIONS - Weekly simple experiments with hypothesis formation, collaborative investigations with shared findings, exploration stations with observational assessment, real-world problem solving using scientific thinking; ORAL ASSESSMENT - Scientific discussions during circle time, peer explanations of observations and discoveries, presentations of findings to classmates or younger students, questioning and wondering sessions demonstrating curiosity; PORTFOLIO DEVELOPMENT - Collection of observational drawings showing scientific detail, photographs of student investigations and discoveries, artifacts from nature walks and explorations, growth documentation in scientific vocabulary and concepts; AUTHENTIC ASSESSMENT - Application of scientific knowledge to classroom problems, connections between scientific learning and daily life, demonstration of care and responsibility for living things, integration of scientific concepts across subject areas.',
  
  indigenousPerspectives = 'Mi''kmaq ecological knowledge integrated throughout scientific learning: Traditional Mi''kmaq understanding of seasonal cycles and natural indicators, shared with cultural protocols and community partnership; Mi''kmaq plant knowledge including traditional uses, sustainable harvesting practices, and medicinal applications appropriate for young learners; Animal relationships and traditional ecological knowledge about local wildlife behavior, migration patterns, and habitat needs; Mi''kmaq astronomy and connection to natural cycles, seasonal stars, and traditional calendar keeping; Water teachings and understanding of sacred relationships with rivers, lakes, and ocean systems; Traditional weather prediction methods and observation of natural signs for seasonal changes; Seven Sacred Teachings connecting to respectful relationships with all living things; Land-based learning opportunities with Indigenous Knowledge Keepers when culturally appropriate; Recognition of Mi''kmaq place names reflecting ecological knowledge and natural features; Integration of traditional ecological practices like companion planting, natural pest management, and sustainable resource use; Acknowledgment of Mi''kmaq stewardship and ongoing relationship with PEI lands and waters.',
  
  resourceLibrary = 'Rich collection of scientific exploration materials: LIVING MATERIALS - Classroom plants for observation and care, butterfly garden or caterpillar habitat, bird feeder and viewing station, seasonal collections of natural specimens, seeds for planting investigations; EXPLORATION TOOLS - Magnifying glasses and simple microscopes, measuring tools for scientific investigations, containers for specimen collection and observation, thermometers for weather tracking, timers for investigation timing; LITERATURE - Science picture books featuring diverse scientists, field guides for local plants and animals, books about seasonal changes and animal adaptations, stories connecting science to Indigenous knowledge, poetry celebrating nature and scientific wonder; DIGITAL RESOURCES - Camera for documenting investigations and changes, weather tracking apps and websites, virtual field trips to natural areas, time-lapse videos of plant growth and seasonal changes; OUTDOOR EQUIPMENT - Garden tools for planting investigations, outdoor thermometers and weather tracking tools, collection containers for nature walks, outdoor seating for scientific observations; REFERENCE MATERIALS - Posters showing local plants, animals, and seasonal cycles, charts for tracking weather and growth, scientific vocabulary cards with visual supports.',
  
  parentCommunication = 'Family engagement extending scientific learning beyond school: NATURE CONNECTION - Weekly suggestions for family nature walks with observation focus, monthly nature scavenger hunts connecting to classroom learning, seasonal celebration activities highlighting scientific observations, encouragement of family gardening and outdoor exploration; HOME SCIENCE - Simple scientific investigations families can do together using household materials, kitchen science activities connecting to classroom concepts, suggestions for scientific observations during family routines, celebration of family knowledge about nature and science; COMMUNITY EXPLORATION - Recommendations for family visits to local natural areas, seasonal activities highlighting scientific phenomena, connections to PEI provincial parks and nature centers, suggestions for citizen science participation; COMMUNICATION - Weekly updates about scientific investigations and discoveries, monthly newsletters explaining scientific concepts and home connections, sharing of classroom scientific achievements and breakthroughs, celebration of student scientific thinking and curiosity; CULTURAL CONNECTIONS - Recognition and celebration of family knowledge about nature and traditional practices, multilingual sharing of scientific vocabulary and concepts, incorporation of diverse cultural approaches to understanding natural world.',
  
  differentiationFramework = 'Inclusive scientific learning for all students: FOR EMERGING SCIENTIFIC THINKERS - Concrete hands-on experiences before abstract concepts; visual supports and graphic organizers for scientific thinking; simplified scientific language with key vocabulary emphasis; extended time for observation and investigation; peer support during scientific collaborations; celebration of scientific curiosity over perfect understanding. FOR ADVANCED SCIENTIFIC LEARNERS - Open-ended investigations with multiple variables; opportunities to design their own scientific experiments; connections to more complex scientific concepts; leadership roles in scientific discussions; independent scientific research projects; extension readings about scientists and scientific discoveries. FOR STUDENTS WITH LEARNING DIFFERENCES - Multi-sensory scientific experiences addressing different learning styles; assistive technology for scientific documentation; alternative methods for showing scientific understanding; modified expectations aligned with individual learning goals; sensory supports for outdoor scientific exploration. FOR ENGLISH LANGUAGE LEARNERS - Scientific learning leveraging universal observation and investigation; visual and hands-on approaches reducing language barriers; peer translation and support when appropriate; celebration of home knowledge about nature and traditional practices; multilingual scientific vocabulary development; recognition that scientific thinking transcends language barriers.'

WHERE subject = 'Sciences de la nature';

-- 4. SCIENCES HUMAINES  
UPDATE LongRangePlan SET 
  thematicOverview = 'Community and identity exploration throughout the year: September - Qui suis-je? (Who Am I?) exploring individual identity, family backgrounds, and personal strengths; October - Ma famille unique (My Unique Family) celebrating diverse family structures, traditions, and cultural backgrounds; November - Notre classe comme communauté (Our Classroom Community) building classroom citizenship, rights, responsibilities, and collaborative decision-making; December - Traditions et célébrations (Traditions and Celebrations) exploring cultural traditions, holiday celebrations, and family customs from diverse backgrounds; January - Notre école et ses règles (Our School and Its Rules) understanding school community, rules, roles, and democratic participation; February - Amitié et résolution de conflits (Friendship and Conflict Resolution) developing social skills, empathy, and peaceful problem-solving strategies; March - Ma communauté locale (My Local Community) exploring neighborhood, local businesses, community helpers, and civic engagement; April - Les cartes et notre monde (Maps and Our World) developing geographic skills, understanding directions, and exploring local and global connections; May - Besoins et désirs (Needs and Wants) understanding economic concepts, making choices, and appreciating resources; June - Être un bon citoyen (Being a Good Citizen) reflecting on community contributions, environmental stewardship, and future aspirations.',
  
  assessmentStrategy = 'Project-based assessment celebrating social understanding: COMMUNITY PROJECTS - Monthly collaborative projects addressing real classroom or school issues, service learning connections to local community needs, student-led initiatives for positive change, documentation of civic engagement and leadership development; FAMILY AND CULTURAL PRESENTATIONS - Student presentations about family traditions and cultural backgrounds, sharing of family artifacts, stories, and celebrations, peer learning about diverse cultural practices and beliefs, development of cultural competency and appreciation; MAPPING AND GEOGRAPHY SKILLS - Progressive development of mapping skills from classroom to community to world, assessment of directional understanding and spatial reasoning, documentation of geographic vocabulary and concept development, real-world application of geographic knowledge; SOCIAL SKILLS ASSESSMENT - Observation of collaborative skills during group projects, conflict resolution strategies in peer interactions, demonstration of empathy and perspective-taking, leadership and citizenship behavior documentation; REFLECTION AND SELF-ASSESSMENT - Regular reflection on community contributions and citizenship goals, self-assessment of social skills development, goal setting for continued growth in social responsibility, celebration of progress in understanding diverse perspectives.',
  
  indigenousPerspectives = 'Authentic integration of Mi''kmaq history, culture, and ongoing presence: Recognition of Mi''kmaq as the first peoples of Prince Edward Island, with age-appropriate understanding of traditional territories and ongoing stewardship; Mi''kmaq family structures and community values explored alongside diverse modern family configurations; Traditional Mi''kmaq governance and decision-making processes introduced as examples of democratic participation and community care; Mi''kmaq place names and their meanings connecting to geographic learning and cultural understanding; Traditional Mi''kmaq seasonal round and connection to land, resources, and sustainable living practices; Seven Sacred Teachings integrated into character education and social skills development; Contemporary Mi''kmaq communities and contributions to PEI society, including artists, leaders, and knowledge keepers; Cultural protocols and respect when learning about Mi''kmaq traditions, with community partnership and guidance; Mi''kmaq rights and treaties presented in age-appropriate ways connecting to citizenship concepts; Integration of Mi''kmaq storytelling traditions and oral history as valuable knowledge systems; Connection to local Mi''kmaq communities for authentic learning opportunities and cultural exchange.',
  
  resourceLibrary = 'Diverse resources supporting social learning: CULTURAL MATERIALS - Books representing diverse family structures, cultures, and traditions; artifacts and images from various cultural backgrounds including Mi''kmaq items with proper protocols; music and stories from different cultural traditions; maps showing cultural diversity locally and globally; celebration materials for various cultural holidays and traditions. COMMUNITY RESOURCES - Local community photos and information, contact information for community helpers and local businesses, maps of local area including Mi''kmaq place names, information about local government and democratic processes, resources about PEI history including Indigenous history; GEOGRAPHIC MATERIALS - Maps of classroom, school, community, PEI, Canada, and world; globes and atlases appropriate for young learners; geographic games and puzzles; photos of different geographic features and environments; tools for creating classroom and individual maps. CITIZENSHIP RESOURCES - Books about rights, responsibilities, and community participation; conflict resolution posters and visual supports; democracy and decision-making tools for classroom use; environmental stewardship materials and activities; service learning project ideas and documentation tools.',
  
  parentCommunication = 'Family partnership in social learning: CULTURAL CELEBRATION - Invitations for families to share cultural traditions, foods, stories, and celebrations with the classroom; family heritage projects connecting home and school learning; multicultural events celebrating the diversity of classroom families; recognition and appreciation of family knowledge and cultural contributions. COMMUNITY CONNECTIONS - Family involvement in community service projects and local engagement opportunities; information about local community events and civic participation; encouragement of family conversations about community issues and solutions; connection to local cultural and historical sites for family exploration. HOME-SCHOOL COLLABORATION - Regular communication about social skills development and citizenship goals; family input on classroom rules, expectations, and community building; collaborative problem-solving when social challenges arise; celebration of family values and approaches to social development. DEMOCRATIC PARTICIPATION - Family involvement in classroom decision-making when appropriate; opportunities for families to contribute expertise and knowledge; recognition of diverse family structures and approaches to community participation; support for families in developing civic engagement and community connections.',
  
  differentiationFramework = 'Inclusive social learning honoring all students: FOR SHY OR INTROVERTED STUDENTS - Multiple ways to participate in social activities including drawing, writing, or small group sharing; respect for different comfort levels with public speaking and group participation; peer buddy systems for social support; celebration of quiet leadership and thoughtful contributions. FOR STUDENTS WITH SOCIAL CHALLENGES - Explicit teaching of social skills with visual supports and practice opportunities; structured social interactions with clear expectations; conflict resolution support and mediation; individual social goals with positive reinforcement systems. FOR ENGLISH LANGUAGE LEARNERS - Social learning leveraging non-verbal communication and universal concepts; peer translation and cultural bridge-building when appropriate; celebration of multilingual and multicultural knowledge; recognition that social intelligence transcends language barriers. FOR STUDENTS FROM DIVERSE BACKGROUNDS - Affirmation and celebration of all family structures, cultural practices, and traditions; anti-bias education addressing stereotypes and promoting inclusion; culturally responsive teaching honoring diverse approaches to community and citizenship; family partnership ensuring cultural respect and authentic representation. FOR STUDENTS WITH LEARNING DIFFERENCES - Alternative methods for demonstrating social understanding; modified expectations for written or verbal expression; assistive technology for social communication when needed; sensory considerations for group activities and community exploration.'

WHERE subject = 'Sciences humaines';

-- 5. ARTS VISUELS
UPDATE LongRangePlan SET 
  thematicOverview = 'Process-focused artistic exploration celebrating creativity: September - Couleurs et émotions (Colors and Emotions) exploring color theory through personal expression and feeling exploration; October - Art dans la nature (Art in Nature) using natural materials for creative expression and environmental art projects; November - Portraits et identité (Portraits and Identity) celebrating individual uniqueness through self-portraits and family representations; December - Art et traditions (Art and Traditions) creating artwork inspired by diverse cultural traditions and holiday celebrations; January - Formes et sculptures (Shapes and Sculptures) exploring 3D art, clay work, and sculptural expression; February - Art communautaire (Community Art) collaborating on large-scale projects and appreciating local artists; March - Printemps créatif (Creative Spring) nature-inspired art connecting to seasonal observations and growth; April - Histoires visuelles (Visual Stories) creating narrative art and illustrated stories; May - Art et techniques (Art and Techniques) exploring various artistic methods, tools, and media; June - Galerie et célébration (Gallery and Celebration) curating student artwork and reflecting on artistic growth.',
  
  assessmentStrategy = 'Portfolio-based assessment honoring artistic process: ARTISTIC PORTFOLIO DEVELOPMENT - Collection of artwork showing progression throughout the year, including initial explorations, works in progress, and final pieces; student reflection on artistic choices, challenges, and discoveries; documentation of different media and technique exploration; celebration of creative risk-taking and experimentation. PROCESS DOCUMENTATION - Photographs of students engaged in artistic creation, showing thinking and problem-solving processes; video recordings of students explaining their artistic decisions and techniques; observation notes during artistic exploration and creation; documentation of collaboration and peer learning during art making. ARTIST STATEMENTS - Age-appropriate reflection on artwork using visual and verbal methods; student explanation of artistic choices, inspirations, and meanings; goal setting for continued artistic growth; celebration of personal artistic voice and expression. PEER FEEDBACK AND COLLABORATION - Structured peer appreciation sessions focusing on artistic effort and creativity; collaborative projects with shared assessment and reflection; learning from classmates'' artistic approaches and techniques; building supportive artistic community. AUTHENTIC ASSESSMENT - Application of artistic skills to cross-curricular projects; real-world artistic problem solving; connection of artwork to personal experiences and cultural backgrounds; demonstration of artistic vocabulary and concept understanding.',
  
  indigenousPerspectives = 'Respectful integration of Mi''kmaq artistic traditions: Traditional Mi''kmaq art forms including beadwork, basket making, and quillwork introduced with cultural protocols and community partnership; Mi''kmaq symbols and their meanings explored with respect and proper cultural context; Traditional colors and materials used in Mi''kmaq art, with understanding of cultural significance; Mi''kmaq pottery and sculpture traditions connecting to 3D art explorations; Traditional Mi''kmaq storytelling through visual art and pictographs; Connection to contemporary Mi''kmaq artists and their contributions to Canadian art; Seasonal art projects reflecting Mi''kmaq understanding of natural cycles and relationships; Collaborative projects with local Mi''kmaq artists when culturally appropriate; Seven Sacred Teachings expressed through artistic creation and reflection; Recognition of art as cultural expression and identity preservation; Land-based art making using traditional materials and approaches with proper guidance.',
  
  resourceLibrary = 'Comprehensive collection of artistic materials: BASIC ART SUPPLIES - Quality paints, brushes, crayons, markers, colored pencils, pastels; various papers including construction, watercolor, and drawing paper; glue, scissors, rulers, and basic art tools; clay and sculpture materials for 3D exploration. NATURAL AND RECYCLED MATERIALS - Collected natural items for art making including leaves, stones, shells, twigs; recycled materials for creative reuse and environmental consciousness; fabric scraps, buttons, and collage materials; natural dyes and pigments for color exploration. CULTURAL ART MATERIALS - Art supplies reflecting diverse cultural traditions; books and images showing art from various cultures including Mi''kmaq traditions; multicultural art examples and inspiration materials; traditional tools and materials when culturally appropriate. TECHNOLOGY AND DIGITAL ARTS - Cameras for documenting artistic process and finished work; simple digital art tools and apps; access to online art museum tours and artist galleries; technology for research about artists and art movements. REFERENCE AND INSPIRATION - Art books featuring diverse artists and art styles; local artist information and community art resources; art posters and prints showing various techniques and approaches; art vocabulary cards with visual examples.',
  
  parentCommunication = 'Family engagement celebrating artistic expression: FAMILY ART NIGHTS - Monthly events where families create art together using techniques learned in class; opportunity for families to experience artistic processes alongside their children; celebration of family creativity and artistic traditions; sharing of cultural art forms and family artistic knowledge. HOME ART CONNECTIONS - Suggestions for simple art activities families can do together using household materials; encouragement of artistic experimentation and creative expression at home; celebration of family artistic traditions and cultural art forms; recognition of art as valuable learning and expression. ARTISTIC CELEBRATION - Regular sharing of student artwork through newsletters, displays, and digital portfolios; family invitations to art shows and student galleries; recognition of artistic growth and creative achievements; celebration of effort and creativity over finished product perfection. CULTURAL ART SHARING - Invitation for families to share artistic traditions and cultural art forms; opportunity for family members to teach traditional art techniques; celebration of diverse artistic backgrounds and cultural expressions; multicultural art appreciation events and activities.',
  
  differentiationFramework = 'Inclusive artistic expression for all learners: FOR STUDENTS NEEDING FINE MOTOR SUPPORT - Adapted art tools and materials for easier manipulation; extended time for artistic creation and detailed work; alternative methods for artistic expression including digital tools; celebration of artistic intention over technical precision. FOR ARTISTICALLY ADVANCED STUDENTS - Access to more complex art materials and techniques; leadership opportunities in peer teaching and collaboration; connections to community artists and advanced artistic exploration; independent artistic projects and investigations. FOR STUDENTS WITH SENSORY DIFFERENCES - Sensory-friendly art materials and alternatives for different sensitivities; quiet spaces for artistic creation when needed; modified materials for tactile sensitivities; celebration of unique sensory approaches to artistic expression. FOR ENGLISH LANGUAGE LEARNERS - Artistic expression as universal language transcending verbal communication; visual vocabulary development through art making; celebration of cultural artistic traditions and home art forms; peer support and collaboration during artistic activities. FOR STUDENTS WITH LEARNING DIFFERENCES - Multiple ways to demonstrate artistic understanding and creativity; assistive technology for artistic access when needed; modified expectations focusing on personal artistic growth; celebration of individual artistic strengths and approaches.'

WHERE subject = 'Arts visuels';

-- 6. FORMATION PERSONNELLE ET SOCIALE
UPDATE LongRangePlan SET 
  thematicOverview = 'Social-emotional learning integrated throughout daily experiences: September - Se connaître soi-même (Getting to Know Myself) exploring personal identity, strengths, and uniqueness; October - Émotions et sentiments (Emotions and Feelings) developing emotional vocabulary and regulation strategies; November - Relations familiales (Family Relationships) appreciating family diversity and building family connections; December - Gratitude et générosité (Gratitude and Generosity) developing appreciation and giving spirit during holiday season; January - Objectifs et résolutions (Goals and Resolutions) setting personal goals and developing growth mindset; February - Amitié et empathie (Friendship and Empathy) building social skills and understanding others'' perspectives; March - Sécurité et bien-être (Safety and Wellness) learning personal safety and wellness strategies; April - Résolution de conflits (Conflict Resolution) developing peaceful problem-solving skills; May - Responsabilité et leadership (Responsibility and Leadership) exploring personal and community responsibility; June - Croissance et avenir (Growth and Future) reflecting on personal development and planning ahead.',
  
  assessmentStrategy = 'Holistic assessment supporting personal and social development: SELF-REFLECTION TOOLS - Weekly check-ins using visual emotion scales and goal-setting sheets; monthly self-assessment of social skills and personal growth; student portfolios including personal artifacts, goals, and reflections; celebration of progress in self-awareness and emotional regulation. SOCIAL SKILLS OBSERVATION - Daily anecdotal notes about social interactions and conflict resolution; documentation of empathy, kindness, and collaborative behavior; observation of leadership and responsibility demonstration; assessment of friendship skills and peer relationships. SAFETY AND WELLNESS DEMONSTRATIONS - Assessment of safety knowledge through role-playing and scenarios; demonstration of wellness habits and self-care strategies; understanding of help-seeking behaviors and trusted adult identification; application of safety rules in various school settings. GOAL SETTING AND ACHIEVEMENT - Regular goal setting for personal and academic growth; documentation of progress toward individual goals; celebration of effort and persistence; reflection on strategies that support success. FAMILY AND COMMUNITY CONNECTIONS - Assessment of family relationship understanding and appreciation; demonstration of community responsibility and citizenship; integration of personal values with family and cultural teachings.',
  
  indigenousPerspectives = 'Seven Sacred Teachings integrated into character development: WISDOM (Nibwaakaawin) - Cherishing knowledge and understanding, seeking guidance from Elders and teachers, appreciating traditional knowledge alongside contemporary learning. LOVE (Zaagi''idiwin) - Developing unconditional love for family, community, and all living things; showing care and compassion in daily interactions. RESPECT (Mnaadendimowin) - Honoring all people, cultures, and living beings; showing respect for differences and diverse ways of being; respecting traditional territories and cultural protocols. TRUTH (Debwewin) - Being honest in words and actions; understanding the importance of truthfulness in relationships; speaking and living authentically. HUMILITY (Dibaadendizwin) - Recognizing individual place in the larger community; appreciating others'' gifts and contributions; understanding interconnectedness with all life. BRAVERY (Aakwe''ewin) - Courage to do what is right even when difficult; facing challenges with inner strength; standing up for others and for justice. HONESTY (Gwekwaadiziwin) - Living with integrity and authenticity; being truthful with self and others; honoring commitments and responsibilities. Integration through daily practices, community circle discussions, and connection to contemporary character education.',
  
  resourceLibrary = 'Comprehensive wellness and social-emotional resources: EMOTIONAL REGULATION TOOLS - Emotion identification charts and feeling wheels; calming strategies posters and visual guides; breathing and mindfulness resources for young learners; comfort items and quiet space materials for self-regulation. SOCIAL SKILLS MATERIALS - Friendship and conflict resolution visual guides; communication skills posters and role-play materials; empathy building books and stories; collaborative games and team-building activities. SAFETY AND WELLNESS RESOURCES - Personal safety books and educational materials; community helper identification and contact information; healthy habits posters and tracking tools; first aid and emergency procedure visual guides. MINDFULNESS AND SELF-CARE - Age-appropriate meditation and relaxation resources; gratitude journals and appreciation activities; nature connection materials for outdoor wellness; movement and yoga resources for physical and emotional regulation. CULTURAL AND FAMILY RESOURCES - Books representing diverse family structures and cultural traditions; materials supporting various religious and spiritual practices; multicultural celebration and tradition resources; family communication and connection activities.',
  
  parentCommunication = 'Family partnership in social-emotional development: WELLNESS COMMUNICATION - Regular updates about social-emotional learning topics and home extension activities; family workshops on supporting emotional regulation and social skills; sharing of strategies that work both at home and school; celebration of family approaches to character development. SAFETY PARTNERSHIPS - Collaboration on safety planning and emergency procedures; family input on safety concerns and community awareness; shared responsibility for teaching personal safety and awareness; communication about school safety procedures and protocols. CHARACTER DEVELOPMENT - Family involvement in goal setting and character education; sharing of family values and cultural approaches to personal development; collaborative support for consistent character expectations; celebration of character growth and positive choices. SOCIAL SKILLS SUPPORT - Communication about friendship challenges and peer relationships; family strategies for supporting social skill development; shared approaches to conflict resolution and problem-solving; celebration of social successes and relationship building. CULTURAL CONNECTIONS - Recognition and integration of family cultural teachings about character and community; respect for diverse approaches to personal and social development; collaboration in connecting school learning to family values and traditions.',
  
  differentiationFramework = 'Individualized support for personal and social growth: FOR STUDENTS WITH SOCIAL-EMOTIONAL CHALLENGES - Individualized behavior plans with positive reinforcement; additional support for emotional regulation and social skills; quiet spaces and calming strategies readily available; collaboration with families and support professionals. FOR STUDENTS WITH TRAUMA EXPERIENCES - Trauma-informed approaches to social-emotional learning; recognition of individual triggers and support needs; emphasis on safety, trust, and relationship building; professional support coordination when needed. FOR STUDENTS WITH AUTISM OR SOCIAL DIFFERENCES - Visual supports and structured social learning opportunities; explicit teaching of social norms and expectations; sensory considerations for social-emotional activities; celebration of neurodivergent approaches to relationships and communication. FOR ENGLISH LANGUAGE LEARNERS - Social-emotional learning that transcends language barriers; peer support and buddy systems; recognition that emotional intelligence and social skills transfer across languages; family cultural approaches to character development. FOR STUDENTS WITH ANXIETY OR MENTAL HEALTH NEEDS - Modified expectations for social participation; additional supports for emotional regulation; family collaboration on mental health strategies; professional support coordination and communication. FOR GIFTED OR ADVANCED LEARNERS - Leadership opportunities in peer support and mentoring; complex social-emotional concepts and ethical discussions; service learning and community contribution opportunities; recognition of perfectionism and social-emotional needs of high achievers.'

WHERE subject = 'Formation personnelle et sociale';

-- 7. ÉDUCATION PHYSIQUE
UPDATE LongRangePlan SET 
  thematicOverview = 'Fundamental movement development through inclusive physical activity: Fall - Locomotor skill development including walking, running, jumping, hopping, and skipping with proper form and safety; spatial awareness activities and movement in personal and general space; cooperative games building teamwork and inclusive participation. Winter - Manipulative skills including throwing, catching, kicking, and striking using various equipment; hand-eye and foot-eye coordination development; introduction to simple games and modified sports activities. Spring - Balance, stability, and gymnastics movements including rolling, weight transfer, and basic sequences; outdoor activities and nature-based movement; culminating physical literacy celebrations and demonstrations.',
  
  assessmentStrategy = 'Movement skill development through observation and student self-assessment: Skill progression checklists for fundamental movement skills; video documentation of movement improvement over time; student self-assessment using visual rubrics; peer observation and positive feedback systems; participation and effort recognition over competitive performance.',
  
  indigenousPerspectives = 'Traditional Indigenous games and physical activities: Integration of traditional Mi''kmaq games when culturally appropriate; understanding of Indigenous approaches to physical activity and community sport; respect for land-based physical activities and outdoor education; incorporation of traditional teamwork and cooperation values.',
  
  resourceLibrary = 'Inclusive physical education equipment: Variety of balls, hoops, scarves, and parachutes; adaptive equipment for students with different abilities; outdoor exploration and nature play materials; safety equipment and first aid supplies; music and rhythm instruments for movement activities.',
  
  parentCommunication = 'Family engagement in active living: Monthly newsletters about physical activities families can do together; information about community recreation opportunities; celebration of diverse family approaches to physical activity; encouragement of outdoor play and nature exploration.',
  
  differentiationFramework = 'Adaptive physical education for all students: Modified equipment and activities for different ability levels; alternative ways to participate and demonstrate physical literacy; peer support systems and inclusive game modifications; celebration of individual progress and effort; collaboration with families and support professionals for students with physical or health needs.'

WHERE subject = 'Éducation physique';

-- 8. MUSIC (English)
UPDATE LongRangePlan SET 
  thematicOverview = 'Musical exploration through creative expression and cultural appreciation: Fall - Sound exploration and rhythm development through body percussion and simple instruments; singing games and folk songs from diverse cultures; introduction to musical concepts of loud/soft and fast/slow. Winter - Melody and singing development with simple songs and vocal play; instrument exploration including classroom percussion; creative movement and dance to various musical styles. Spring - Musical creativity through composition and improvisation; performance preparation and sharing; appreciation of diverse musical traditions and community musicians.',
  
  assessmentStrategy = 'Creative musical assessment through performance and reflection: Performance assessments focusing on participation and musical expression; creative composition projects using simple instruments and voice; listening skills development through musical games and activities; student reflection on musical preferences and growth.',
  
  indigenousPerspectives = 'Integration of Indigenous musical traditions: Exposure to Mi''kmaq traditional songs and instruments when culturally appropriate; understanding of music as cultural expression and storytelling; respect for Indigenous approaches to musical education and community celebration.',
  
  resourceLibrary = 'Diverse musical resources and instruments: Classroom percussion instruments and simple melodic instruments; recordings of music from various cultures and traditions; music education games and activities; technology for music creation and exploration.',
  
  parentCommunication = 'Family involvement in musical learning: Information about musical activities and concepts being learned; suggestions for musical activities families can enjoy together; celebration of family musical traditions and cultural songs; invitations to musical performances and sharing events.',
  
  differentiationFramework = 'Inclusive musical education for all learners: Adaptive instruments and alternative participation methods; visual and kinesthetic approaches to musical learning; respect for different comfort levels with singing and performance; celebration of diverse musical backgrounds and cultural traditions; support for students with hearing differences or other special needs.'

WHERE subject = 'Music';

-- Verify the updates
SELECT subject, 
       CASE WHEN thematicOverview IS NOT NULL THEN 'Yes' ELSE 'No' END as ThematicOverview,
       CASE WHEN assessmentStrategy IS NOT NULL THEN 'Yes' ELSE 'No' END as AssessmentStrategy,
       CASE WHEN indigenousPerspectives IS NOT NULL THEN 'Yes' ELSE 'No' END as IndigenousPerspectives,
       CASE WHEN resourceLibrary IS NOT NULL THEN 'Yes' ELSE 'No' END as ResourceLibrary,
       CASE WHEN parentCommunication IS NOT NULL THEN 'Yes' ELSE 'No' END as ParentCommunication,
       CASE WHEN differentiationFramework IS NOT NULL THEN 'Yes' ELSE 'No' END as DifferentiationFramework
FROM LongRangePlan 
ORDER BY subject;