-- ETFO-Compliant Assessment Criteria for Unit: "grandir" (Formation personnelle et sociale)
-- Grade 1 French Immersion - Developmentally Appropriate and Emotionally Supportive
-- Generated by pedagogical expert following ETFO assessment principles

-- Assessment for lesson: Je grandis chaque jour
-- Learning Goals: Identifier le concept de je grandis; Pratiquer les habiletés de vie quotidienne; Développer l'autonomie par des situations authentiques
-- Curriculum Expectation: FPS1.2 - Reconnaître l'importance de l'hygiène personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève identifie des signes de croissance physique (taille, dents, cheveux)", "L''élève nomme des activités qu''il peut faire maintenant mais pas avant", "L''élève démontre des habitudes d''hygiène personnelle de base", "L''élève exprime avec fierté ses nouveaux apprentissages", "L''élève participe aux discussions sur la croissance de façon positive"],"checkpoints":["Reconnaît au moins 3 changements dans sa croissance", "Démontre l''autonomie dans les routines d''hygiène quotidienne"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vj00cfvj9tlvxh1xgy';

-- Assessment for lesson: Mes changements spéciaux
-- Learning Goals: Explorer le concept de mes changements; Pratiquer les habiletés de vie quotidienne; Développer l'autonomie par des situations authentiques
-- Curriculum Expectation: FPS1.1 - Identifier les habitudes de vie saines
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève décrit des changements positifs qu''il remarque chez lui", "L''élève identifie des habitudes saines qu''il pratique", "L''élève exprime ses sentiments face aux changements de façon appropriée", "L''élève respecte les différences de croissance chez ses pairs", "L''élève utilise un vocabulaire français approprié pour décrire les changements"],"checkpoints":["Nomme au moins 3 habitudes de vie saines qu''il pratique", "Exprime positivement ses propres changements et ceux des autres"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vk00chvj9tp1ewssr2';

-- Assessment for lesson: Célébrer nos familles
-- Learning Goals: Découvrir la famille et ses membres; Pratiquer les rôles familiaux avec respect; Développer l'autonomie par des situations authentiques
-- Curriculum Expectation: FPS1.5 - Comprendre la sécurité personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève décrit sa famille avec respect et fierté", "L''élève nomme les rôles et responsabilités des membres de sa famille", "L''élève identifie les personnes de confiance dans sa famille", "L''élève respecte la diversité des structures familiales", "L''élève exprime l''amour et l''appartenance à sa famille"],"checkpoints":["Identifie au moins 3 personnes de confiance dans son environnement familial", "Démontre le respect envers toutes les formes de familles"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vk00cjvj9t9g3y2b5x';

-- Assessment for lesson: Mes souvenirs de bébé
-- Learning Goals: Coopérer le concept de mes souvenirs; Pratiquer les habiletés de vie quotidienne; Développer l'autonomie par des situations authentiques
-- Curriculum Expectation: FPS1.4 - Pratiquer des stratégies de gestion du stress
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève partage des souvenirs ou photos de quand il était bébé", "L''élève compare ce qu''il pouvait faire avant et maintenant", "L''élève exprime des émotions positives en parlant de ses souvenirs", "L''élève utilise des stratégies de relaxation quand il se sent nostalgique", "L''élève écoute respectueusement les souvenirs des autres"],"checkpoints":["Identifie au moins 3 différences entre bébé et maintenant", "Utilise au moins une stratégie pour gérer les émotions fortes"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vl00clvj9t49kps518';

-- Assessment for lesson: Mes amis changent aussi
-- Learning Goals: Pratiquer l'amitié positive; Pratiquer les habiletés de vie quotidienne; Développer la régulation émotionnelle par des situations authentiques
-- Curriculum Expectation: FPS1.3 - Identifier les émotions de base
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève nomme des émotions qu''il ressent face aux changements chez ses amis", "L''élève identifie les émotions de base (joie, tristesse, colère, peur)", "L''élève démontre de l''empathie envers les sentiments de ses pairs", "L''élève pratique des habiletés d''amitié positive et inclusive", "L''élève utilise des mots pour exprimer ses émotions plutôt que des comportements"],"checkpoints":["Identifie et nomme au moins 4 émotions de base", "Démontre des stratégies d''amitié positive dans ses interactions"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vm00cnvj9tgpnpm19v';

-- Assessment for lesson: Mes rêves pour grandir
-- Learning Goals: Développer le concept de mes rêves; Pratiquer les habiletés de vie quotidienne; Développer la régulation émotionnelle par des situations authentiques
-- Curriculum Expectation: FPS1.2 - Reconnaître l'importance de l'hygiène personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève exprime ses rêves et aspirations pour l''avenir", "L''élève comprend que grandir nécessite des soins personnels", "L''élève démontre des habitudes d''hygiène liées à ses objectifs de croissance", "L''élève utilise des stratégies pour gérer l''excitation ou l''anxiété face à l''avenir", "L''élève respecte les rêves et objectifs de ses pairs"],"checkpoints":["Exprime au moins 3 rêves réalistes pour son avenir", "Connecte l''importance de l''hygiène personnelle à ses objectifs de croissance"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vn00cpvj9telx0dx4f';

-- Assessment for lesson: Nos traditions de classe
-- Learning Goals: Exprimer le concept de nos traditions; Pratiquer les habiletés de vie quotidienne; Développer la régulation émotionnelle par des situations authentiques
-- Curriculum Expectation: FPS1.1 - Identifier les habitudes de vie saines
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève identifie les traditions positives de la classe", "L''élève participe respectueusement aux traditions établies", "L''élève propose des idées pour de nouvelles traditions saines", "L''élève comprend comment les traditions créent un sentiment d''appartenance", "L''élève démontre des habitudes saines dans les activités de classe"],"checkpoints":["Nomme au moins 3 traditions de classe et leur importance", "Propose au moins une tradition saine pour la classe"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vo00crvj9t8k8lyzhl';

-- Assessment for lesson: Capsule temporelle
-- Learning Goals: Gérer le concept de capsule temporelle; Pratiquer les habiletés de vie quotidienne; Développer la régulation émotionnelle par des situations authentiques
-- Curriculum Expectation: FPS1.5 - Comprendre la sécurité personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève sélectionne des objets significatifs représentant qui il est maintenant", "L''élève explique pourquoi certains souvenirs sont précieux et personnels", "L''élève comprend l''importance de garder certaines choses privées et sécurisées", "L''élève gère ses émotions face au passage du temps", "L''élève respecte l''intimité et les souvenirs personnels des autres"],"checkpoints":["Choisit au moins 3 objets significatifs pour sa capsule avec explications", "Démontre la compréhension de l''intimité personnelle et du respect"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vp00ctvj9t1u9qyp6y';

-- Assessment for lesson: Histoires de famille
-- Learning Goals: Coopérer la famille et ses membres; Raconter les rôles familiaux avec respect; Développer les habiletés sociales par la narration
-- Curriculum Expectation: FPS1.4 - Pratiquer des stratégies de gestion du stress
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève raconte des histoires de famille avec fierté et respect", "L''élève identifie les rôles et contributions des membres de sa famille", "L''élève utilise la narration comme stratégie pour gérer les émotions", "L''élève écoute activement et respectueusement les histoires des autres", "L''élève utilise des stratégies de relaxation quand les histoires provoquent des émotions fortes"],"checkpoints":["Raconte au moins une histoire de famille positive avec détails", "Utilise la narration ou l''écoute comme stratégie de gestion émotionnelle"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vp00cvvj9t3e9p5tab';

-- Assessment for lesson: Mes moments de fierté
-- Learning Goals: Pratiquer le concept de mes moments; Pratiquer les habiletés de vie quotidienne; Développer les habiletés sociales par des situations authentiques
-- Curriculum Expectation: FPS1.3 - Identifier les émotions de base
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève identifie des moments personnels qui lui procurent de la fierté", "L''élève nomme l''émotion de fierté et la distingue des autres émotions", "L''élève exprime sa fierté de manière appropriée et humble", "L''élève célèbre les réussites et moments de fierté de ses pairs", "L''élève utilise ses moments de fierté pour développer sa confiance en soi"],"checkpoints":["Identifie au moins 3 moments personnels de fierté avec explications", "Démontre la reconnaissance et célébration des réussites d''autrui"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vq00cxvj9tqpfaibji';

-- Assessment for lesson: Grandir ensemble à l'école
-- Learning Goals: Développer l'école et ses routines; Pratiquer les habiletés de vie quotidienne; Développer les habiletés sociales par des situations authentiques
-- Curriculum Expectation: FPS1.2 - Reconnaître l'importance de l'hygiène personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève identifie comment il a grandi depuis le début de l''année scolaire", "L''élève démontre l''indépendance dans les routines scolaires", "L''élève maintient une bonne hygiène personnelle à l''école", "L''élève aide ses pairs dans leurs routines et croissance", "L''élève exprime un sentiment d''appartenance à la communauté scolaire"],"checkpoints":["Identifie au moins 3 façons dont il a grandi à l''école cette année", "Démontre l''autonomie dans au moins 2 routines scolaires importantes"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vr00czvj9tdo474odh';

-- Assessment for lesson: Célébrer nos apprentissages
-- Learning Goals: Exprimer le concept de célébrer nos; Pratiquer les habiletés de vie quotidienne; Développer les habiletés sociales par des situations authentiques
-- Curriculum Expectation: FPS1.1 - Identifier les habitudes de vie saines
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève identifie et célèbre ses apprentissages académiques et personnels", "L''élève reconnaît l''effort et le progrès plutôt que seulement les résultats", "L''élève démontre des habitudes d''apprentissage saines", "L''élève encourage et célèbre les apprentissages de ses pairs", "L''élève exprime de la gratitude pour ses opportunités d''apprentissage"],"checkpoints":["Nomme au moins 3 apprentissages significatifs de l''année", "Démontre au moins 2 habitudes d''apprentissage saines qu''il a développées"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vs00d1vj9tk8rv5ecl';

-- Assessment for lesson: Portfolio de croissance
-- Learning Goals: Gérer le concept de portfolio de; Pratiquer les habiletés de vie quotidienne; Développer la conscience de soi par des situations authentiques
-- Curriculum Expectation: FPS1.5 - Comprendre la sécurité personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève organise soigneusement des éléments représentant sa croissance", "L''élève explique pourquoi certains travaux sont importants pour lui", "L''élève comprend l''importance de garder son portfolio personnel en sécurité", "L''élève respecte l''intimité de son portfolio et celui des autres", "L''élève démontre de la fierté appropriée dans la présentation de son travail"],"checkpoints":["Sélectionne au moins 5 éléments significatifs pour son portfolio avec justifications", "Démontre la compréhension de la confidentialité et du respect des travaux personnels"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vt00d3vj9t0mul6hlz';

-- Assessment for lesson: Présentation de croissance
-- Learning Goals: Coopérer le concept de présentation de; Présenter les habiletés de vie quotidienne; Développer la conscience de soi par le partage des apprentissages
-- Curriculum Expectation: FPS1.4 - Pratiquer des stratégies de gestion du stress
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève présente sa croissance avec confiance et clarté", "L''élève utilise des stratégies pour gérer le stress de présenter devant les autres", "L''élève écoute respectueusement les présentations de ses pairs", "L''élève pose des questions appropriées et offre des compliments", "L''élève gère ses émotions avant, pendant et après sa présentation"],"checkpoints":["Présente sa croissance de façon organisée en incluant au moins 3 domaines", "Utilise au moins 2 stratégies pour gérer le stress de la présentation"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vu00d5vj9t3z4pj2sq';

-- Assessment for lesson: Jeu de mémoire de croissance
-- Learning Goals: Pratiquer le concept de jeu de; Participer à les habiletés de vie quotidienne; Développer la conscience de soi par le jeu dirigé
-- Curriculum Expectation: FPS1.3 - Identifier les émotions de base
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève participe activement au jeu en identifiant des moments de croissance", "L''élève nomme les émotions associées aux différentes étapes de sa croissance", "L''élève fait preuve de fair-play et encourage les autres joueurs", "L''élève utilise sa mémoire pour rappeler des événements significatifs de croissance", "L''élève exprime du plaisir et de l''engagement dans l''activité ludique"],"checkpoints":["Identifie correctement au moins 5 émotions liées à la croissance dans le jeu", "Démontre des comportements de jeu coopératif et respectueux"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vv00d7vj9t98d2ygj4';

-- Assessment for lesson: Art de croissance créatif
-- Learning Goals: Développer le concept de art de; Pratiquer les habiletés de vie quotidienne; Développer la conscience de soi par des situations authentiques
-- Curriculum Expectation: FPS1.2 - Reconnaître l'importance de l'hygiène personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève crée une œuvre d''art représentant sa croissance personnelle", "L''élève prend soin de ses matériaux artistiques et de son espace de travail", "L''élève exprime sa créativité tout en maintenant de bonnes habitudes d''hygiène", "L''élève explique comment son art reflète sa croissance et ses apprentissages", "L''élève respecte et apprécie les créations artistiques de ses pairs"],"checkpoints":["Crée une œuvre d''art personnelle incluant au moins 3 éléments de sa croissance", "Démontre des habitudes de propreté et de soin des matériaux pendant l''activité créative"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vw00d9vj9tcx62wwgd';

-- Assessment for lesson: Théâtre de traditions familiales
-- Learning Goals: Exprimer le concept de théâtre de; Pratiquer les habiletés de vie quotidienne; Développer la résilience par des situations authentiques
-- Curriculum Expectation: FPS1.1 - Identifier les habitudes de vie saines
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève participe au théâtre en représentant des traditions familiales saines", "L''élève identifie et mime des habitudes de vie saines de sa famille", "L''élève fait preuve de résilience face au défi de performer devant les autres", "L''élève respecte et célèbre la diversité des traditions familiales présentées", "L''élève utilise l''expression théâtrale pour communiquer des valeurs positives"],"checkpoints":["Présente au moins 2 traditions familiales saines à travers le jeu théâtral", "Démontre la résilience et la confiance en participant activement à la performance"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vx00dbvj9tvy431pt3';

-- Assessment for lesson: Livre de classe collectif
-- Learning Goals: Appliquer le concept de livre de; Pratiquer les habiletés de vie quotidienne; Développer la résilience par des situations authentiques
-- Curriculum Expectation: FPS1.5 - Comprendre la sécurité personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève contribue de façon appropriée au livre collectif de la classe", "L''élève comprend l''importance de partager seulement des informations sécuritaires", "L''élève respecte l''intimité personnelle tout en participant au projet collectif", "L''élève démontre de la résilience en travaillant en collaboration", "L''élève célèbre les contributions de tous les membres de la classe"],"checkpoints":["Contribue au livre collectif en partageant des informations appropriées et sécuritaires", "Démontre la compréhension des limites personnelles dans le partage d''informations"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vy00ddvj9tg9bs3hsc';

-- Assessment for lesson: Fête de croissance
-- Learning Goals: Maintenir le concept de fête de; Pratiquer les habiletés de vie quotidienne; Développer la résilience par des situations authentiques
-- Curriculum Expectation: FPS1.2 - Reconnaître l'importance de l'hygiène personnelle
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève participe joyeusement à la célébration de la croissance collective", "L''élève maintient une bonne hygiène personnelle durant les activités de fête", "L''élève démontre de la résilience en célébrant ses propres défis surmontés", "L''élève encourage et félicite sincèrement la croissance de ses pairs", "L''élève exprime de la gratitude pour son parcours de croissance"],"checkpoints":["Participe activement à la fête en célébrant au moins 3 aspects de sa croissance", "Maintient des habitudes d''hygiène appropriées dans le contexte social de la fête"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3vz00dfvj9tthkvjwyw';

-- Assessment for lesson: Réflexion sur notre voyage
-- Learning Goals: Adopter le concept de réflexion sur; Pratiquer les habiletés de vie quotidienne; Développer la résilience par des situations authentiques
-- Curriculum Expectations: FPS1.2 - Reconnaître l'importance de l'hygiène personnelle; FPS1.3 - Identifier les émotions de base
UPDATE ETFOLessonPlan 
SET assessmentNotes = '{"observable":["L''élève réfléchit de façon mature sur son voyage de croissance durant l''année", "L''élève identifie et nomme les émotions ressenties durant différentes étapes", "L''élève reconnaît l''importance des soins personnels dans sa croissance", "L''élève démontre de la résilience en parlant des défis qu''il a surmontés", "L''élève exprime de la fierté et de la gratitude pour son parcours d''apprentissage"],"checkpoints":["Réfléchit sur son voyage en identifiant au moins 4 émotions différentes vécues", "Connecte l''importance de l''hygiène et des soins personnels à sa croissance globale"]}',
    assessmentType = 'formative'
WHERE id = 'cmf43u3w000dhvj9tizov2gni';

-- ASSESSMENT SUMMARY FOR "GRANDIR" UNIT
-- =====================================
-- 
-- Unit: "grandir" (Formation personnelle et sociale)
-- Total lessons assessed: 20
-- All assessments: Formative (ETFO-compliant)
-- 
-- KEY PEDAGOGICAL FEATURES:
-- • Emotionally supportive language throughout
-- • Developmentally appropriate for Grade 1 (ages 5-6)
-- • All criteria in French for immersion context
-- • Focus on observable behaviors and clear milestones
-- • Sensitive handling of personal growth topics
-- • Inclusive of diverse family structures and experiences
-- • Emphasis on emotional safety and respect
-- 
-- CURRICULUM ALIGNMENT:
-- • FPS1.1: Identifier les habitudes de vie saines (4 lessons)
-- • FPS1.2: Reconnaître l'importance de l'hygiène personnelle (6 lessons)
-- • FPS1.3: Identifier les émotions de base (4 lessons)  
-- • FPS1.4: Pratiquer des stratégies de gestion du stress (3 lessons)
-- • FPS1.5: Comprendre la sécurité personnelle (3 lessons)
-- • Multi-expectation lessons: 1 lesson (lesson 20)
--
-- ASSESSMENT PRINCIPLES APPLIED:
-- • Formative assessment focus for ongoing learning
-- • Multiple ways to demonstrate understanding
-- • Respectful of cultural and family diversity
-- • Age-appropriate emotional support strategies
-- • Clear, measurable criteria for teachers
-- • Positive reinforcement of growth mindset
