name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRISMA_NO_ENGINE_DOWNLOAD: '1'
      PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: '1'
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 10.11.1 # keep this in sync with local version

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify Jest and Prisma availability
        run: |
          pnpm exec jest --version
          pnpm exec prisma --version

      - name: Generate Prisma Client
        run: pnpm db:generate

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Lint
        run: pnpm run lint

      - name: Install dependencies before build/test
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Playwright E2E Tests
        run: pnpm playwright:test
