name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRISMA_NO_ENGINE_DOWNLOAD: '1'
      PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: '1'
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10.11.1 # keep this in sync with local version

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify Jest and Prisma availability
        run: |
          pnpm --filter server exec jest --version
          pnpm --filter @teaching-engine/database exec prisma --version

      - name: Generate Prisma Client
        run: pnpm db:generate

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Lint
        run: pnpm run lint

      - name: Verify docs
        run: pnpm run check:docs

      - name: Build
        run: pnpm run build

      - name: Test
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
          JWT_SECRET: test-secret-key
          JWT_EXPIRES_IN: 1h
        run: pnpm run test

      - name: Deploy database schema
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
        run: pnpm db:deploy

      - name: Seed database
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
        run: pnpm db:seed

      - name: Playwright API Tests
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
          JWT_SECRET: test-secret-key
          JWT_EXPIRES_IN: 1h
          NODE_ENV: test
          PORT: 3000
          CI: true
        run: |
          echo "Starting API smoke tests..."
          echo "DATABASE_URL: $DATABASE_URL"
          echo "Checking database file:"
          ls -la packages/database/prisma/test.db || echo "Database file not found"
          pnpm exec playwright test tests/e2e/api-smoke.spec.ts --reporter=list || (echo "API tests failed. Uploading artifacts..." && exit 1)

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
