name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRISMA_NO_ENGINE_DOWNLOAD: '1'
      PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: '1'
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10.11.1 # keep this in sync with local version

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify Jest and Prisma availability
        run: |
          pnpm --filter server exec jest --version
          pnpm --filter @teaching-engine/database exec prisma --version

      - name: Generate Prisma Client
        run: pnpm db:generate

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Lint
        run: pnpm run lint

      - name: Verify docs
        run: pnpm run check:docs

      - name: Build
        run: pnpm run build

      - name: Test
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
          JWT_SECRET: test-secret-key
          JWT_EXPIRES_IN: 1h
        run: pnpm run test

      - name: Deploy database schema
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
        run: pnpm db:deploy

      - name: Seed database
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
        run: pnpm db:seed

      - name: Start backend server
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
          JWT_SECRET: test-secret-key
          JWT_EXPIRES_IN: 1h
          NODE_ENV: test
          PORT: 3000
        run: |
          echo "Starting backend server..."
          cd server && nohup pnpm start > server.log 2>&1 &
          echo "Waiting for backend to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:3000/api/health > /dev/null; then
              echo "Backend is ready!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Backend failed to start. Server log:"
              cat server.log
              exit 1
            fi
            sleep 2
          done

      - name: Run API Tests
        env:
          DATABASE_URL: file:./packages/database/prisma/test.db
          JWT_SECRET: test-secret-key
          JWT_EXPIRES_IN: 1h
          NODE_ENV: test
          CI: true
        run: |
          echo "Running API smoke tests..."
          cd server && pnpm test src/__tests__/simpleTest.ts || true
          cd ..
          pnpm exec playwright test tests/e2e/api-smoke.spec.ts --reporter=list

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
